-- Run this entire file once in Supabase: SQL Editor → New query → paste → Run
-- This creates all tables GamePulse needs and fixes 404 errors from the app.

-- Visits (optional logging)
create table if not exists public.visits (
  id bigint generated by default as identity primary key,
  path text,
  created_at timestamptz default now()
);
alter table public.visits enable row level security;
drop policy if exists "allow inserts from anon" on public.visits;
create policy "allow inserts from anon"
  on public.visits for insert to anon with check (true);

-- Profiles (Discord login + DM notifications)
create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  username text,
  avatar_url text,
  discord_id text,
  created_at timestamptz default now(),
  updated_at timestamptz default now()
);
alter table public.profiles enable row level security;
alter table public.profiles add column if not exists discord_id text;
drop policy if exists "Users can read own profile" on public.profiles;
create policy "Users can read own profile" on public.profiles for select using (auth.uid() = id);
drop policy if exists "Users can insert own profile" on public.profiles;
create policy "Users can insert own profile" on public.profiles for insert with check (auth.uid() = id);
drop policy if exists "Users can update own profile" on public.profiles;
create policy "Users can update own profile" on public.profiles for update using (auth.uid() = id);

-- Subscriptions (subscribe to games for Discord DMs)
create table if not exists public.subscriptions (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  game_id text not null,
  created_at timestamptz default now(),
  unique(user_id, game_id)
);
alter table public.subscriptions enable row level security;
drop policy if exists "Users can read own subscriptions" on public.subscriptions;
create policy "Users can read own subscriptions" on public.subscriptions for select using (auth.uid() = user_id);
drop policy if exists "Users can insert own subscriptions" on public.subscriptions;
create policy "Users can insert own subscriptions" on public.subscriptions for insert with check (auth.uid() = user_id);
drop policy if exists "Users can delete own subscriptions" on public.subscriptions;
create policy "Users can delete own subscriptions" on public.subscriptions for delete using (auth.uid() = user_id);

-- Game updates cache (for notify-subscribers cron)
create table if not exists public.game_updates_cache (
  game_id text primary key,
  last_title text,
  last_url text,
  last_date timestamptz,
  updated_at timestamptz default now()
);
alter table public.game_updates_cache enable row level security;
